import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;

export { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
export type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

import {
  faBell,
  faBuildingColumns,
  faCalendarDays,
  faChartLine,
  faCheck,
  faCircleCheck,
  faCircleExclamation,
  faCopy,
  faCreditCard,
  faEye,
  faEyeSlash,
  faGift,
  faHistory,
  faHouse,
  faLock,
  faArrowRight,
  faArrowUpRightFromSquare,
  faBolt,
  faPlus,
  faPaperPlane,
  faRightFromBracket,
  faRotate,
  faShieldHalved,
  faWandMagicSparkles,
  faUpload,
  faUser,
  faWallet,
  faXmark,
  faCircleQuestion,
  faEnvelope,
  faPhone,
  faGear,
  faUsers,
  faFileInvoice,
  faMoneyBillTransfer,
  faSliders,
  faDatabase,
  faDownload,
  faTrash,
  faPen,
  faPlay,
  faBars,
} from '@fortawesome/free-solid-svg-icons';

import { faGoogle, faApple } from '@fortawesome/free-brands-svg-icons';

export const icons = {
  bell: faBell,
  bank: faBuildingColumns,
  calendar: faCalendarDays,
  chart: faChartLine,
  check: faCheck,
  circleCheck: faCircleCheck,
  circleExclamation: faCircleExclamation,
  copy: faCopy,
  creditCard: faCreditCard,
  eye: faEye,
  eyeSlash: faEyeSlash,
  gift: faGift,
  history: faHistory,
  home: faHouse,
  lock: faLock,
  arrowRight: faArrowRight,
  arrowUpRight: faArrowUpRightFromSquare,
  bolt: faBolt,
  plus: faPlus,
  send: faPaperPlane,
  logout: faRightFromBracket,
  refresh: faRotate,
  shield: faShieldHalved,
  sparkles: faWandMagicSparkles,
  upload: faUpload,
  user: faUser,
  wallet: faWallet,
  close: faXmark,
  help: faCircleQuestion,
  mail: faEnvelope,
  phone: faPhone,
  gear: faGear,
  users: faUsers,
  file: faFileInvoice,
  transfer: faMoneyBillTransfer,
  sliders: faSliders,
  database: faDatabase,
  download: faDownload,
  trash: faTrash,
  edit: faPen,
  play: faPlay,
  menu: faBars,
  google: faGoogle,
  apple: faApple,
} as const;

export type IconName = keyof typeof icons;
